version: '2.3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./docker-dir/db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    container_name: wallet_postgres

  wallet:
    network_mode: "host"
    ports:
      - "9999:9999"
    build:
      context: docker-dir
      dockerfile: Dockerfile
    depends_on:
      - db